#!/usr/bin/env bash

# Shared defaults for MeshtasticBridge scripts.
# Override any value by exporting it before running a script.

export APP_PORT="${APP_PORT:-8090}"
export MESHTASTIC_HOST_DEVICE=/dev/ttyACM1
export MESHTASTIC_DEVICE="${MESHTASTIC_DEVICE:-/dev/ttyACM1}"
export MESHTASTIC_CALLSIGN="${MESHTASTIC_CALLSIGN:-BRIDGE}"
export MESHTASTIC_ACCEPT_BROADCAST="${MESHTASTIC_ACCEPT_BROADCAST:-true}"
export MESHTASTIC_CONNECT_ON_START="${MESHTASTIC_CONNECT_ON_START:-true}"
export MESHTASTIC_CONNECT_TIMEOUT="${MESHTASTIC_CONNECT_TIMEOUT:-300}"
export MESHTASTIC_RECONNECT_INTERVAL="${MESHTASTIC_RECONNECT_INTERVAL:-30}"
export LOG_LEVEL="${LOG_LEVEL:-INFO}"

export DOCKER_IMAGE="${DOCKER_IMAGE:-meshtasticbridge}"
export DOCKER_CONTAINER="${DOCKER_CONTAINER:-meshtasticbridge}"

# Use these when the host serial path differs from the path inside Docker.
export MESHTASTIC_DEVICE_IN_HOST="${MESHTASTIC_DEVICE_IN_HOST:-$MESHTASTIC_DEVICE}"
export MESHTASTIC_DEVICE_IN_HOST="${MESHTASTIC_HOST_DEVICE}"
export MESHTASTIC_DEVICE_IN_DOCKER="${MESHTASTIC_DEVICE_IN_DOCKER:-$MESHTASTIC_DEVICE}"
